/**
 * MCP server configuration — updates .mcp.json (and .codex/config.toml
 * for OpenAI Codex) based on the user's Figma integration choice.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

/**
 * Configure .mcp.json based on Figma choice.
 *
 * @param {'console'|'devmode'|'both'|'skip'} figmaChoice
 * @param {string|null} figmaToken  — null if skip
 * @param {string}      root        — absolute path to repo root
 * @param {boolean}     removingAllJs — if true, also remove storybook server
 */
export function configureMcp(figmaChoice, figmaToken, root, removingAllJs) {
  const mcpPath = resolve(root, '.mcp.json');
  const mcp = JSON.parse(readFileSync(mcpPath, 'utf-8'));

  // Remove servers based on Figma choice
  if (figmaChoice === 'console') {
    delete mcp.mcpServers['figma'];
  } else if (figmaChoice === 'devmode') {
    delete mcp.mcpServers['figma-console'];
  }
  // 'both' → keep both; 'skip' → keep both with placeholder token

  // Inject real token if provided
  if (figmaToken && figmaChoice !== 'skip') {
    if (mcp.mcpServers['figma-console']) {
      mcp.mcpServers['figma-console'].env.FIGMA_ACCESS_TOKEN = figmaToken;
    }
    if (mcp.mcpServers['figma']) {
      mcp.mcpServers['figma'].env.FIGMA_ACCESS_TOKEN = figmaToken;
    }
  }

  // Remove storybook server if all JS frameworks are gone
  if (removingAllJs) {
    delete mcp.mcpServers['storybook'];
  }

  writeFileSync(mcpPath, JSON.stringify(mcp, null, 2) + '\n', 'utf-8');
}

/**
 * Configure .codex/config.toml to match the .mcp.json configuration.
 * Called only when the user selects OpenAI Codex as their IDE.
 *
 * @param {'console'|'devmode'|'both'|'skip'} figmaChoice
 * @param {string|null} figmaToken  — null if skip
 * @param {string}      root        — absolute path to repo root
 * @param {boolean}     removingAllJs — if true, also remove storybook server
 */
export function configureCodexMcp(figmaChoice, figmaToken, root, removingAllJs) {
  const codexDir = resolve(root, '.codex');
  if (!existsSync(codexDir)) {
    mkdirSync(codexDir, { recursive: true });
  }
  const tomlPath = resolve(codexDir, 'config.toml');

  const token = (figmaToken && figmaChoice !== 'skip') ? figmaToken : 'YOUR_FIGMA_TOKEN_HERE';

  const sections = [];

  // Header
  sections.push(
    '# Codex MCP Server Configuration (project-scoped)',
    '# Mirrors .mcp.json — auto-generated by setup wizard',
    '# Docs: https://developers.openai.com/codex/mcp/',
    ''
  );

  // Figma Console MCP
  if (figmaChoice !== 'devmode') {
    sections.push(
      '[mcp_servers.figma-console]',
      'command = "npx"',
      'args = ["-y", "figma-console-mcp@latest"]',
      '',
      '[mcp_servers.figma-console.env]',
      `FIGMA_ACCESS_TOKEN = "${token}"`,
      'ENABLE_MCP_APPS = "true"',
      ''
    );
  }

  // Figma Dev Mode MCP
  if (figmaChoice !== 'console') {
    sections.push(
      '[mcp_servers.figma]',
      'command = "npx"',
      'args = ["-y", "@anthropic/figma-mcp-server"]',
      '',
      '[mcp_servers.figma.env]',
      `FIGMA_ACCESS_TOKEN = "${token}"`,
      ''
    );
  }

  // Storybook MCP (unless all JS frameworks removed)
  if (!removingAllJs) {
    sections.push(
      '[mcp_servers.storybook]',
      'command = "npx"',
      'args = ["-y", "@anthropic/storybook-mcp-server"]',
      '',
      '[mcp_servers.storybook.env]',
      'STORYBOOK_URL = "http://localhost:6006"',
      ''
    );
  }

  // Playwright MCP
  sections.push(
    '[mcp_servers.playwright]',
    'command = "npx"',
    'args = ["-y", "@playwright/mcp@latest"]',
    ''
  );

  writeFileSync(tomlPath, sections.join('\n'), 'utf-8');
}
